"""
Model planning

User table:
Many users may use this project, so we need a table for storing their telegram_id

    id: Integer, primary key, autoincrement
    telegram_id: Integer, unique, not null
    username: String, nullable

username is optional since with the telegram_id is enough to identify a user.

Expense table:
We want to store the amount and the user. Also a optional comment regarding the expense.
The category will come later as a relationship with the category table so we
can have a many to one relationship with the category table to have multiple
categories.

    id: Integer, primary key, autoincrement
    user_id: Integer, ForeignKey to User table, not null
    amount: Float, not null
    comment: String, nullable


Category table:
Category id (autogenerated) and category name (unique) are enough to identify a category.

    category_id: Integer, primary key, autoincrement
    category_name: String, unique, not null

Its important that "food" is equal to "Food"

Expense X Category table:
We want to have a many to many relationship between the expense and category table.

    expense_id: Integer, ForeignKey to Expense table, not null
    category_id: Integer, ForeignKey to Category table, not null
"""

from datetime import datetime, timezone

from sqlalchemy import Column, Integer, Float, String, Table, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from db.database import Base

# Middle table between expenses and categories
expense_categories = Table(
    "expense_categories",
    Base.metadata,
    Column("expense_id", Integer, ForeignKey("expenses.id"), primary_key=True),
    Column("category_id", Integer, ForeignKey("categories.id"), primary_key=True),
)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    telegram_id = Column(Integer, unique=True, nullable=False)
    username = Column(String, nullable=True)

    expenses = relationship("Expense", back_populates="user")

    def __repr__(self):
        return f"<User(id={self.id}, telegram_id={self.telegram_id}, username={self.username})>"


class Expense(Base):
    __tablename__ = "expenses"

    id = Column(Integer, primary_key=True, autoincrement=True)
    amount = Column(Float, nullable=False)
    timestamp = Column(
        DateTime, default=lambda: datetime.now(timezone.utc), nullable=False
    )
    user_id = Column(Integer, ForeignKey("users.id"))
    comment = Column(String, nullable=True)

    user = relationship("User", back_populates="expenses")
    categories = relationship(
        "Category", secondary=expense_categories, back_populates="expenses"
    )

    def __repr__(self):
        return f"<Expense(id={self.id}, amount={self.amount}, user_id={self.user_id}, comment={self.comment}, categories={self.categories}) timestamp={self.timestamp})>"


class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, unique=True, nullable=False)

    expenses = relationship(
        "Expense", secondary=expense_categories, back_populates="categories"
    )

    def __repr__(self):
        return f"<Category(id={self.id}, name={self.name})>"
